return {
  'NvChad/nvim-colorizer.lua',
  event = { 'BufReadPost', 'BufNewFile' },
  config = function()
    require('colorizer').setup({
      filetypes = {
        'css',
        'scss',
        'sass',
        'less',
        'html',
        'xml',
        'svg',
        'lua',
        'vim',
        'toml',
        'yaml',
        'json',
        'jsonc',
        'javascript',
        'javascriptreact',
        'typescript',
        'typescriptreact',
        'conf',
        css = { css = true, names = true },
        scss = { css = true, names = true },
        html = { names = true },
        lua = { names = true },
      },
      user_default_options = {
        RGB = true,
        RRGGBB = true,
        RRGGBBAA = true,
        rgb_fn = true,
        hsl_fn = true,
        css = true,
        css_fn = true,
        mode = 'virtualtext',
        virtualtext = '■',
        tailwind = false,
      },
    })
  end,
}
