#!/usr/bin/env bash
# install-ast-grep.sh - Install or update ast-grep (structural code search).
# Re-run anytime: it compares the installed binary against the latest release
# and only downloads when a newer one exists. --force reinstalls regardless.
# Assumes: Linux x86_64 (sudo), curl + jq + sha256sum + awk + unzip + dpkg,
# network. dpkg is used only for `--compare-versions`; upstream ships no .deb.
# Installs the release binary after verifying GitHub's SHA-256 digest, plus a
# bash completion generated by the binary itself.
#
# The release zip also contains `sg`, a deprecated alias that warns on every
# run. It is deliberately not installed: `sg` is already /usr/bin/sg from the
# `login` package (run a command under a different group id), and shadowing a
# system binary is not worth a shim upstream tells you not to use.

set -euo pipefail # Exit on error, unset vars, and pipe failures

REPO="ast-grep/ast-grep"
BINARY="ast-grep"
ASSET_NAME="app-x86_64-unknown-linux-gnu.zip" # carries no version of its own
INSTALL_DIR="/usr/local/bin"
COMPLETION_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/bash-completion/completions"
WORK_DIR="$(mktemp -d "${TMPDIR:-/tmp}/ast-grep-install.XXXXXX")"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(git -C "$SCRIPT_DIR" rev-parse --show-toplevel 2>/dev/null || printf '%s\n' "${SCRIPT_DIR%/*}")"

# shellcheck source=tools/lib/github-release.sh
source "$SCRIPT_DIR/lib/github-release.sh"

# Clean up the work dir on any exit (success, error, or interrupt)
trap 'rm -rf "$WORK_DIR"' EXIT

gh_parse_force_flag "$@"
gh_require_linux_x86_64
gh_require_cmds unzip dpkg

echo "Resolving latest ast-grep release..."
gh_resolve_latest "$REPO"
echo "Latest version:    $GH_VERSION"

# `ast-grep --version` prints a single "ast-grep <version>" line.
INSTALLED=""
if command -v "$BINARY" >/dev/null 2>&1; then
    INSTALLED=$("$BINARY" --version 2>/dev/null | awk 'NR == 1 {print $2}')
fi
echo "Installed version: ${INSTALLED:-none}"

NEED_BINARY=1
if gh_up_to_date "$INSTALLED" "$GH_VERSION"; then
    NEED_BINARY=0
fi

# Tracked separately from the binary: the completion can go missing on its own
# (a re-apply, a manual cleanup) while the binary is perfectly current, and that
# case should self-heal instead of requiring --force.
NEED_COMPLETION=1
[[ -f "$COMPLETION_DIR/$BINARY" ]] && NEED_COMPLETION=0

# The completions directory is a `tree` row in the manifest precisely so it
# stays a real directory that third-party installers can write into. If it is
# ever a symlink into the repo, installing through it would commit ast-grep's
# completion as a tracked file -- so refuse and name the fix instead.
COMPLETION_TARGET="$(readlink -f "$COMPLETION_DIR")"
if [[ "$COMPLETION_TARGET" == "$REPO_ROOT"/* ]]; then
    echo ""
    echo "Warning: $COMPLETION_DIR resolves into the dotfiles repo:"
    echo "         $COMPLETION_TARGET"
    echo "         Installing there would commit ast-grep's completion as a tracked file."
    echo "         The scripts rows must be MODE=tree in the manifest; check with:  dots status scripts"
    echo "         Skipping the completion for now."
    NEED_COMPLETION=0
    SKIPPED_COMPLETION=1
fi

if ((FORCE)); then
    if ((NEED_BINARY == 0)); then
        echo "Reinstalling anyway (--force)..."
    fi
    NEED_BINARY=1
    ((${SKIPPED_COMPLETION:-0})) || NEED_COMPLETION=1
fi

if ((NEED_BINARY == 0 && NEED_COMPLETION == 0)); then
    echo ""
    echo "✓ ast-grep is already up to date."
    exit 0
fi

if ((NEED_BINARY)); then
    echo "Downloading ast-grep $GH_VERSION..."
    gh_fetch_asset "$ASSET_NAME" "$WORK_DIR/$ASSET_NAME"

    # -j flattens, and naming the member extracts only it -- `sg` stays in the
    # zip. unzip fails if the member is absent, so a reshaped release is caught
    # here rather than by installing whatever happened to be inside.
    echo "Extracting..."
    if ! unzip -o -j -q "$WORK_DIR/$ASSET_NAME" "$BINARY" -d "$WORK_DIR"; then
        echo "Error: failed to extract $BINARY from $ASSET_NAME" >&2
        exit 1
    fi
    chmod +x "$WORK_DIR/$BINARY"

    echo "Testing binary..."
    if ! "$WORK_DIR/$BINARY" --version >/dev/null 2>&1; then
        echo "Error: downloaded ast-grep is not working properly" >&2
        exit 1
    fi

    echo "Installing to $INSTALL_DIR (requires sudo)..."
    if ! sudo install "$WORK_DIR/$BINARY" -D -t "$INSTALL_DIR"; then
        echo "Error: failed to install ast-grep to $INSTALL_DIR" >&2
        exit 1
    fi
    hash -r 2>/dev/null || true
fi

if ((NEED_COMPLETION)); then
    # Generated by the binary that was just installed, so the completion can
    # never describe a version other than the one on disk. bash-completion
    # loads on demand from the XDG data dir, keyed on the command name, so no
    # shell rc changes are needed.
    echo "Installing bash completion to $COMPLETION_DIR..."
    if ! "$INSTALL_DIR/$BINARY" completions bash >"$WORK_DIR/completion"; then
        echo "Error: failed to generate the bash completion" >&2
        exit 1
    fi
    mkdir -p "$COMPLETION_DIR"
    install -m 0644 "$WORK_DIR/completion" "$COMPLETION_DIR/$BINARY"
fi

echo ""
echo "✓ ast-grep is installed."
"$INSTALL_DIR/$BINARY" --version

RESOLVED="$(command -v "$BINARY" || true)"
if [[ "$RESOLVED" != "$INSTALL_DIR/$BINARY" ]]; then
    echo ""
    echo "Warning: '$BINARY' on PATH resolves to ${RESOLVED:-nothing}, not $INSTALL_DIR/$BINARY."
    echo "         Another install is shadowing this one (npm and cargo both"
    echo "         publish ast-grep). Remove it, or put $INSTALL_DIR earlier in PATH."
fi

echo ""
echo "Installation location: $INSTALL_DIR/$BINARY"
if ((${SKIPPED_COMPLETION:-0} == 0)); then
    echo "Bash completion:       $COMPLETION_DIR/$BINARY (new shells pick it up)"
fi
echo ""
echo "Search structurally without a config file:"
echo ""
echo "    ast-grep run -p 'console.log(\$\$\$)' -l js"
echo ""
echo "Project-wide linting reads sgconfig.yml from the project root, so"
echo "nothing user-global is deployed for it (\`ast-grep new\` scaffolds one)."
